---
name: 'Setup MQ Client'
description: 'Setup a specific version of MQ Client'
author: 'SeyfSV'
branding:
  icon: 'download'  
  color: 'blue'
inputs:
  mq-client-version:
    description: 'MQ Client version'
    required: true
  mq-file-path:
    description: 'Path to MQ Client location'
    required: false
    default: 
  download-path:
    description: 'Path to redistributable archive location'
    require: false
    default: setup-mqclient
  force-download:
    description: 'Force archive redownload even archive already exists in download-path'
    require: false
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
