---
name: 'Setup MQ Client'
description: 'Setup a specific version of MQ Client'
author: 'SeyfSV'
branding:
  icon: 'download'
  color: 'blue'
inputs:
  clean-mq-file-path:
    description: 'Force cleanup of `mq-file-path` directory'
  mq-client-version:
    description: 'MQ Client version'
    required: true
  mq-file-path:
    description: 'Path to MQ Client location'
    required: false
    default: ''
  mq-data-path:
    description: 'Path to MQ Client `data` directory'
    required: false
    default: ''
  download-path:
    description: 'Path to redistributable archive location'
    required: false
    default: distr
  force-download:
    description: 'Force archive redownload even archive already exists in download-path'
    required: false
    default: 'false'
outputs:
  mq-file-path:
    description: 'Path to MQ Client location'
  mq-client-version:
    description: 'Installed MQ Client version'

runs:
  using: 'node12'
  main: 'dist/index.js'
