name: readme
on: [push]

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Install MQ Client
        uses: SeyfSV/setup-mqclient@v0.2
        with:
          mq-client-version: 9.2.3.0 # Exact version of a client or toolkit
      - run: dspmqver
  caching_n_matrix:
    strategy:
      matrix:
        environment: ["macos-latest", "windows-latest", "ubuntu-latest"]
        mq-client-version: [9.2.2.0, 9.2.3.0, latest]
    runs-on: ${{ matrix.environment}}
    steps:
      - name: Cache MQ Client
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/distr
          key: mqclient-${{ runner.os }}-${{ matrix.mq-client-version }}

      - name: Install MQ Client
        uses: SeyfSV/setup-mqclient@v0.2
        with:
          mq-client-version: ${{ matrix.mq-client-version }}
          download-path: ${{ github.workspace }}/distr
      - run: dspmqver
