name: tests
on: [push]

jobs:
  test_default_job:
    strategy:
      matrix:
        environment: ['macos-latest', 'windows-latest', 'ubuntu-latest']
        mq-client-version: [9.2.2.0, 9.2.3.0]
    runs-on: ${{ matrix.environment}}
    steps:
      - name: Cache MQ Client
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/distr
          key: mqclient-${{ runner.os }}-${{ matrix.mq-client-version }}

      - name: Checkout action
        uses: actions/checkout@v2

      - name: Install MQ Client
        uses: ./
        with:
          mq-client-version: ${{ matrix.mq-client-version }}

      - name: Run dspmqver
        run: dspmqver

  test_custom_job:
    strategy:
      matrix:
        environment: ['macos-latest', 'windows-latest', 'ubuntu-latest']
        mq-client-version: [9.2.2.0, 9.2.3.0]
    runs-on: ${{ matrix.environment}}
    steps:
      - name: Cache MQ Client
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/distr/test-path
          key: mqclient-${{ runner.os }}-${{ matrix.mq-client-version }}-test-path

      - name: Checkout action
        uses: actions/checkout@v2

      - name: Install MQ Client
        uses: ./
        with:
          mq-client-version: ${{ matrix.mq-client-version }}
          mq-file-path: mq-file-path/data
          download-path: ${{ github.workspace }}/distr/test-path

      - name: Run dspmqver
        run: dspmqver