name: tests
on: [push]

jobs:
  test_default_job:
  # Run action only with required parameter `matrix.mq-client-version`
    strategy:
      matrix:
        environment: ["macos-latest", "windows-latest", "ubuntu-latest"]
        mq-client-version: [9.3.0.0, 9.3.1.0, latest]
    runs-on: ${{ matrix.environment}}

    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Cache MQ Client
        uses: actions/cache@v2
        if: ${{ !env.ACT && matrix.mq-client-version != 'latest' }}
        with:
          path: ${{ github.workspace }}/distr
          key: mqclient-${{ runner.os }}-${{ matrix.mq-client-version }}

      - name: Install MQ Client
        uses: ./
        with:
          mq-client-version: ${{ matrix.mq-client-version }}

      - name: Run dspmqver
        run: dspmqver

  test_custom_job:
  # Run action with with non-required parameter `matrix.mq-client-version`
    strategy:
      matrix:
        environment: ["macos-latest", "windows-latest", "ubuntu-latest"]
        mq-client-version: [9.3.0.0, 9.3.3.0]
    runs-on: ${{ matrix.environment}}
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Cache MQ Client
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: distr/test-path
          key: mqclient-${{ runner.os }}-${{ matrix.mq-client-version }}-test-path
          restore-keys: mqclient-${{ runner.os }}-

      - name: Install MQ Client
        uses: ./
        with:
          mq-client-version: ${{ matrix.mq-client-version }}
          mq-file-path: mq-file-path/data
          download-path: distr/test-path
          clean-mq-file-path: false

      - name: Run dspmqver
        run: dspmqver

  test_wrong_version_job:
    strategy:
      matrix:
        environment: ["macos-latest", "windows-latest", "ubuntu-latest"]
        mq-client-version: [0.0.0.0]
    runs-on: ${{ matrix.environment}}
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Cache MQ Client
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: distr/test-path
          key: mqclient-${{ runner.os }}-${{ matrix.mq-client-version }}-test-path
          restore-keys: mqclient-${{ runner.os }}-

      - name: Install MQ Client
        id: install_mq_client
        uses: ./
        with:
          mq-client-version: ${{ matrix.mq-client-version }}
          mq-file-path: mq-file-path/data
          download-path: distr/test-path
        continue-on-error: true

      - name: Fail if previous success
        if: ${{ steps.install_mq_client.outcome == 0 }}
        run: exit 1

  test_overwrite_false_job:
  # Check action fail in case of mq-file-path directory existence
    strategy:
      matrix:
        environment: ["macos-latest", "windows-latest", "ubuntu-latest"]
        mq-client-version: [9.3.0.0]
    runs-on: ${{ matrix.environment}}
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Cache MQ Client
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ github.workspace }}/distr/test-path
          key: mqclient-${{ runner.os }}-${{ matrix.mq-client-version }}-test-path
          restore-keys: mqclient-${{ runner.os }}-

      - name: Install MQ Client
        uses: ./
        with:
          mq-client-version: ${{ matrix.mq-client-version }}
          mq-file-path: mq-file-path/data
          download-path: ${{ github.workspace }}/distr/test-path

      - name: Install MQ Client (2)
        id: install_mq_client
        uses: ./
        with:
          mq-client-version: ${{ matrix.mq-client-version }}
          mq-file-path: mq-file-path/data
          download-path: ${{ github.workspace }}/distr/test-path
        continue-on-error: true

      - name: Fail if previous success
        if: ${{ steps.install_mq_client.outcome == 0 }}
        run: exit 1

  test_overwrite_true_job:
    strategy:
      matrix:
        environment: ["macos-latest", "windows-latest", "ubuntu-latest"]
        mq-client-version: [9.3.0.0]
    runs-on: ${{ matrix.environment}}
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Cache MQ Client
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ github.workspace }}/distr/test-path
          key: mqclient-${{ runner.os }}-${{ matrix.mq-client-version }}-test-path
          restore-keys: mqclient-${{ runner.os }}-

      - name: Install MQ Client
        uses: ./
        with:
          mq-client-version: ${{ matrix.mq-client-version }}
          mq-file-path: mq-file-path/data
          download-path: ${{ github.workspace }}/distr/test-path

      - name: Install MQ Client (2)
        uses: ./
        with:
          mq-client-version: ${{ matrix.mq-client-version }}
          mq-file-path: mq-file-path/data
          download-path: ${{ github.workspace }}/distr/test-path
          clean-mq-file-path: true
